apiVersion: v1
kind: Service
metadata:
  name: kuberservice
spec:
  selector:
    app: kuberapiuser
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberdeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kuberapiuser
  template:
    metadata:
      labels:
        app: kuberapiuser
    spec:
      containers:
        - name: kubecontainers
          image: arturoverbel/apiusers:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always